name: Deploy Website

on:
  push:
    branches:
      - main  # Dieser Workflow wird ausgeführt, wenn etwas in den "main"-Branch gepusht wird

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub verwendet eine virtuelle Ubuntu-Maschine, um den Job auszuführen

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Diese Aktion klont dein Repository in die virtuelle Maschine

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SERVER }}" > ~/.ssh/id_ed25519  # Fügt den SSH-Schlüssel ein
          chmod 600 ~/.ssh/id_ed25519  # Setzt die richtigen Berechtigungen für den Schlüssel
          eval "$(ssh-agent -s)"  # Startet den ssh-agent
          echo "${{ secrets.PP }}" | ssh-add ~/.ssh/id_ed25519  # Fügt den SSH-Schlüssel mit der Passphrase hinzu
          ssh-keyscan -p 52123 85.214.106.223 >> ~/.ssh/known_hosts  # Fügt den Host zur known_hosts Datei hinzu

      - name: Test SSH connection
        run: |
          sshpass -p "${{ secrets.PP }}" ssh -vvv -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p 52123 jhahn@85.214.106.223 "echo SSH connection successful"


      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.PP }}" scp -P 52123 -r ./* jhahn@85.214.106.223:/var/www/html/klapp.pizza/  # Kopiert alle Dateien auf deinen Server und nutzt Port 3123
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER }}  # Nutzt den Secret, den du vorher eingerichtet hast
          SSH_PASSPHRASE: ${{ secrets.PP }}  # Nutzt den Secret für die Passphrase
