name: Deploy Website

on:
  push:
    branches:
      - main  # Dieser Workflow wird ausgeführt, wenn etwas in den "main"-Branch gepusht wird

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub verwendet eine virtuelle Ubuntu-Maschine, um den Job auszuführen

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Diese Aktion klont dein Repository in die virtuelle Maschine

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SERVER1 }}" > ~/.ssh/id_rsa  # Fügt den SSH-Schlüssel ein
          chmod 600 ~/.ssh/id_rsa  # Setzt die richtigen Berechtigungen für den Schlüssel

      - name: Deploy to Server
        run: |
          scp -P 52123 -r ./* jhahn@85.214.106.223:/home  # Kopiert alle Dateien auf deinen Server
        env:
          SERVER1: ${{ secrets.SERVER1 }}  # Nutzt den Secret, den du vorher eingerichtet hast
